version: '3.7'

services:
  reverse-proxy:
    build: ./
    container_name: "nginx-reverse-proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CERT_BASE_PATH}:/certs
    networks:
      - proxynet

networks:
  proxynet:
    name: reverse-proxy-net