version: '3.7'

services:
  reverse-proxy:
    build: ./
    container_name: "nginx-reverse-proxy"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CERT_BASE_PATH}:/certs